apiVersion: v1
kind: Service
metadata:
  name: backend-user
  namespace: staging
  labels:
    app: backend-user
spec:
  type: NodePort
  selector:
    app: backend-user
  ports:
  - port: 3020
    protocol: TCP
    targetPort: 3020
    nodePort: 30020