apiVersion: v1
kind: Service
metadata:
  name: backend-scm
  namespace: staging
  labels:
    app: backend-scm
spec:
  type: NodePort
  selector:
    app: backend-scm
  ports:
  - port: 3030
    protocol: TCP
    targetPort: 3030
    nodePort: 30030