apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-scm
  labels:
    app: backend-scm
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend-scm
  template:
    metadata:
      labels:
        app: backend-scm
    spec:
      containers:
      - name: backend-scm
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.container.port }}
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: questcode
                key: NODE_ENV
          - name: "GITHUB_CLIENT_ID"
            valueFrom:
                configMapKeyRef:
                  name: questcode
                  key: "GITHUB_CLIENT_ID"
          - name: SECRET_OR_KEY
            valueFrom:
                secretKeyRef:
                  name: questcode
                  key: SECRET_OR_KEY
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: questcode
                  key: GITHUB_CLIENT_SECRET
