kind: Service
apiVersion: v1
metadata:
  name: backend-scm
spec:
  type: NodePort
  selector:
    app: backend-scm
  ports:
  - protocol: TCP
    port: {{ .Values.container.port }}
    targetPort: 3030
    nodePort: {{ .Values.service.nodePort }}