apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.container.port }}
        env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: questcode
                key: NODE_ENV
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: questcode
                key: MONGO_URI
          - name: SECRET_OR_KEY
            valueFrom:
                secretKeyRef:
                  name: questcode
                  key: SECRET_OR_KEY