kind: Service
apiVersion: v1
metadata:
  name: backend-user
spec:
  type: NodePort
  selector:
    app: backend-user
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: 3020
      nodePort: {{ .Values.service.nodePort }}
